name: Kotol kernul

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
           swap-size-gb: 12
      
      - name: Setup and Build
        run: |
           sudo apt-get update
           sudo apt install nano bc bison curl flex gcc git libc6-dev libssl-dev openssl python-is-python3 ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu -y && sudo apt install python3 -y && sudo apt install cpio -y && sudo apt install lld -y && sudo apt install llvm -y
        
           export TZ="Asia/Jakarta"
           echo "BUILD_TIME=$(date +"%Y%m%d")-$(date +"%H%M%S")" >> $GITHUB_ENV
        
      - name: build kernel
        run: |
           curl -LSs "https://raw.githubusercontent.com/dreamsolister26/clarinet/refs/heads/main/kernul.sh" | bash
      
      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Kernel-${{ env.BUILD_TIME }}
          path: |
             ${{ github.workspace }}/kernel/*.zip
             ${{ github.workspace }}/kernel/*.log
          
